name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Person/Person.sln

      - name: Publish application
        run: dotnet publish src/Person/Person.Server/Person.Server.csproj -c Release -o PersonPublish

      - name: Build app Docker image
        run: |
          docker build -t person-service:latest ./
          docker save person-service:latest > person.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: person.tar

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run Unit Tests
        run: dotnet test src/Person/Person.sln

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: app-image

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy files to server and deploy
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no person.tar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:/home/rsoi1/app/
          sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:/home/rsoi1/app/
          sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no postgres/10-create-user-and-db.sql ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:/home/rsoi1/app/postgres

          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} docker load -i person.tar
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} docker-compose up -d











  # integration-tests:
  #   name: Autograding
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     # TODO build, test and deploy project

  #     - name: Run API Tests
  #       uses: matt-ball/newman-action@master
  #       with:
  #         collection: postman/[inst] Lab1.postman_collection.json
  #         environment: postman/[inst][heroku] Lab1.postman_environment.json
  #         delayRequest: 100
  #         reporters: '[ "cli" ]'

  #     - name: Autograding
  #       uses: education/autograding@v1
  #       continue-on-error: true

  #     - name: Github auto grader mark
  #       uses: Romanow/google-sheet-autograder-marker@v1.0
  #       with:
  #         google_token: ${{secrets.GOOGLE_API_KEY}}
  #         sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
  #         homework_number: 1
  #         user_column: 'D'
  #         column_offset: 'F'
  #         mark: "'+"